name: SaveDockerImage to Webdav

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Image name'
        required: true
        default: ''
      platform:
        description: 'Image Arch[amd64 arm64 ...]'
        required: true
        default: 'amd64'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: SetUp Evn
        run: |
         mkdir output
         echo platform=${{ github.event.inputs.platform }} image=${{ github.event.inputs.imageName }}
      - name: Pull Image
        run: |
         docker pull --platform ${{ github.event.inputs.platform }} ${{ github.event.inputs.imageName }}
      - name: Check Images
        run: |
         docker images
      - name: Build Souece File
        run: |
         docker save ${{ github.event.inputs.imageName }} > image.tar
      - name: save image to webdav
        run: npm run push ${{ github.event.inputs.imageName }}
        env:
          DAV_URL: ${{ secrets.DAV_URL }}
          DAV_USER: ${{ secrets.DAV_USER }}
          DAV_PASS: ${{ secrets.DAV_PASS }}
